export const ROUTES = {
  login: "/",
  register: "/register",
  dashboard: "/dashboard",
  product: "/product",
  barcodeLabels: "/barcode-labels",
  category: "/category",
  supplier: "/supplier",
  restock: "/restock",
  stockHistory: "/stock-history",
  cashier: "/cashier",
  transactions: "/transactions",
  transactionDetail: "/transactions/:id",
  transactionHistory: "/transaction-history",
  report: "/report",
  setting: "/setting",
  userSettings: "/user-settings",
  storeManagement: "/store-management",
  roleManagement: "/role-management",
  helpShortcut: "/help",
  notifications: "/notifications",
  acceptOwnership: "/accept-ownership",
} as const;
