export const ROUTES = {
  login: "/",
  dashboard: "/dashboard",
  product: "/product",
  category: "/category",
  supplier: "/supplier",
  purchaseOrder: "/purchase-orders",
  cashier: "/cashier",
  transactions: "/transactions",
  transactionDetail: "/transactions/:id",
  transactionHistory: "/transaction-history",
  report: "/report",
  setting: "/setting",
  helpShortcut: "/help",
  notifications: "/notifications",
} as const;
